export type stateTypes = {
    Abia: string[],

    Adamawa: string[],
    "Akwa Ibom": string[],
    Anambra: string[],
    Bauchi: string[],
    Benue: string[],
    Borno: string[],
    Bayelsa: string[],
    "Cross River": string[],
    Delta: string[],
    Ebonyi: string[],
    Edo: string[],
    Ekiti: string[],
    Enugu: string[],
    "Federal Capital Territory": string[],
    Gombe: string[],
    Imo: string[],
    Jigawa: string[],
    Kebbi: string[],
    Kaduna: string[],
    Kano: string[],
    Kogi: string[],
    Katsina: string[],
    Kwara: string[],
    Lagos: string[],
    Nassarawa: string[],
    Niger: string[],
    Ogun: string[],
    Ondo: string[],
    Osun: string[],
    Oyo: string[],
    Plateau: string[],
    Rivers: string[],
    Sokoto: string[],
    Taraba: string[],
    Yobe: string[],
    Zamfara: string[]
}